### ISSUE TITLE
Allow value mapping for aggregation bucket labels

### ISSUE THREAD

**Issue by Glignos** [inveniosoftware/react-searchkit#131]

**Comment by Glignos** [comment]
An example configuration for this functionality would be: `[{'aggName': 'access_right',
           'field': 'access_right',
           'title': 'Access_right',
           'mapping': {'open': 'Open'}},
          {'aggName': 'resource_type',
           'field': 'resource_type.type',
           'title': 'Resource_type'}]`

**Comment by lnielsen** [comment]
Should be done on the REST API level.

**Comment by ntarocco** [comment]
This is was discussed in the vocabularies context and ILS implementation: such mapping is too simplistic. Limitations:
* thousands of possible values, which cannot be easily done via an object mapping like in the example
* it does not allow translations

We should find a solution when implementing vocabularies.
