### ISSUE TITLE
Count: number format

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/react-searchkit#169]
The counts components should format their numbers to improve readability. Ideally it should provide support for internationalization; otherwise we should stick to one locale for consistency (say `en_US`).
For instance in the following case:

![image](https://user-images.githubusercontent.com/9027075/102597917-95517c80-411b-11eb-8b08-894be7e46f0b.png)

...it should instead be displayed as:

![image](https://user-images.githubusercontent.com/9027075/102598013-b2864b00-411b-11eb-87fb-2fa31e0d70d4.png)

There is another "count" component in the aggregation list, and which should also benefit from this feature:

![image](https://user-images.githubusercontent.com/9027075/102598204-f1b49c00-411b-11eb-92bd-590d970bc9d2.png)

**Comment by magistrfox** [comment]
Hey! I guess method ".toLocalString()" is exactly what it needs here.

**Comment by FlorianCassayre** [comment]
Yes indeed, implementation should be quite straightforward. Feel free to submit a pull request :slightly_smiling_face:

**Comment by magistrfox** [comment]
> Yes indeed, implementation should be quite straightforward. Feel free to submit a pull request 🙂

Permission denied. What should I do with that?
