### ISSUE TITLE
Getting started instructions fail

### ISSUE THREAD

**Issue by tonicebrian** [inveniosoftware/react-searchkit#184]
Package version (if known): v1.0.0-alpha.14 

## Describe the bug
Following  instructions literally from https://inveniosoftware.github.io/react-searchkit/docs/getting-started produces the following compilation error:

```
Compiling...
/home/cebrian/borralodedentro/search-app/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

[Error: ENOENT: no such file or directory, stat '/initrd.img'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/initrd.img'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Steps to Reproduce
1. Follow instructions in https://inveniosoftware.github.io/react-searchkit/docs/getting-started
2. When running `yarn start` you'll see the compilation error

## Expected behavior
Demo application up and running

## Additional context
Used:
- node v15.13.0
- npx 6.14.8
- yarn 1.22.5

**Comment by jrcastro2** [comment]
Hi @tonicebrian it might be that you are missing some required modules, try to run this command to add them:
```bash
npm install axios react-overridable react-redux react-thunk redux-thunk semantic-ui-react
```
Thanks for reporting this, we will update the getting started guide.
Please let us know if this solved your problem.

**Comment by tonicebrian** [comment]
I solved the problem by removing all the node modules in my computer and reinstalling them again. I still don't know what was going on.
