### ISSUE TITLE
UI: reset filters when changing query string

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/react-searchkit#2]
When changing query string, some filters should be reset, which one?
For example, if I am in page 300, and I change query string, I should start again from page 1.

**solution**

When changing query string and hitting search:
* if query string empty sort by/order put to default
* pagination back to 1

What should stay:
* aggregations
* results per page
* sort by/order if query string not empty

**Comment by zzacharo** [comment]
Implemented.
