### ISSUE TITLE
Elasticsearch connection goes in Timeout in Searchkit

### ISSUE THREAD

**Issue by kundansmart501** [inveniosoftware/react-searchkit#204]
Package version : 0.1.0

## Describe the bug
I am running searchkit with elasticsearch. It works perfectly fine but after a few days, elasticsearch connection goes in timeout. When I restart the Nginx server, it starts working. The memory usage of the instance looks ok when the searchkit -> elasticsearch goes down. 
Elasticsearch keeps serving the requests during its lost connection in searchkit. So, no downtime of elasticsearch.

## Steps to Reproduce
1. Connect Searchkit with Elastisearch(proxy)
2. Host it through Nginx on AWS instance
3. Keep it running for a few days and keep using it frequently 
4. Elasticsearch connection timeout can be seen in the network console.

Can anyone please help me?

Thanks

**Comment by ntarocco** [comment]
Sorry to hear that, but I really doubt it is related to React-SearchKit: this library is only a client performing queries and it does not keep connections/sockets open. You will have to ask to the Elasticsearch support for help.
