### ISSUE TITLE
Pagination and results per page conditional rendering

### ISSUE THREAD

**Issue by Ducica** [inveniosoftware/react-searchkit#267]
The pagination component as well as results per page, should have a bit different condition for being rendered in my  opinion. I.e. they should only be rendered when totalResults>currentSize && currentSize>-1 (and not as currently currentSize > -1 && totalResults > 0). 

When we get very few results, we have a situation where the pagination with one page only just sits there, takes up space and frankly looks weird (same goes for results per page i.e. it is unnecessary when totalResults<currentSize). Currently, you need to  wrap it with your own component that uses withState and then conditionally render as suggested above, which just bloats the code for no reason and is not very convenient to do in some cases and looks like it would be best handled on the level of component itself.

**Comment by ntarocco** [comment]
It makes sense to make this behaviour configurable: as a generic principle, we tend to avoid hiding components from the UI so that users can comprehend what is happening. This use case though makes a lot of sense.
If you need this soon, would you be available to create a PR?

**Comment by Ducica** [comment]
@ntarocco Hi Nicola, it is not some critical issue for us, but I would be OK to make a PR for it. It should probably be during next week. I will let you know when it is done and then I assume you would give me permissions to push to this repo and also let me know the person I should put as a reviewer. Have a nice evening.

**Comment by Ducica** [comment]
@ntarocco Hi Nicola, I've prepared a small PR for this subject. Could you please allow me to push to the repo as well as the name of the reviewer. Thanks.

**Comment by ntarocco** [comment]
> @ntarocco Hi Nicola, I've prepared a small PR for this subject. Could you please allow me to push to the repo as well as the name of the reviewer. Thanks.

Thank you, please fork this repo and create a PR from the fork.

**Comment by ntarocco** [comment]
Closed by: https://github.com/inveniosoftware/react-searchkit/pull/268

**Comment by Ducica** [comment]
@ntarocco You are welcome Nicola. If it would be OK for you, I would also solve

https://github.com/inveniosoftware/react-invenio-forms/issues/236

and 

https://github.com/inveniosoftware/react-invenio-forms/issues/230

Which are causing us issues. Especially the accordion issue, as our users would like to have some accordions folded when the form first loads and it is just not possible to do at the moment. I am thinking this could be done in one PR. If you agree, let me know please, I would probably get to it by end of this week.
