### ISSUE TITLE
Allow custom rendering of AggregatorValues

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/react-searchkit#57]
The ``Aggregator`` component accepts a ``renderElement`` function to change the way it is displayed. However, the ``AggregatorValues`` are always displayed as a nested list of checkboxes.

Would it be possible to make that customizable? E.g. I want to show it as a Tabbed Menu (that would affect the search by restricting to it, therefore an aggregator).

The ``AggregatorValues`` already has a parameter ``renderElement`` but it does not make use of it.

**Comment by ntarocco** [comment]
Done
