### ISSUE TITLE
InvenioSearchApi: accidental use of both "baseURL" and "url" config

### ISSUE THREAD

**Issue by slint** [inveniosoftware/react-searchkit#88]
axios supports [both `url` and `baseURL` parameters](https://github.com/axios/axios#request-config), setting an absolute `url` though (i.e. `url: "https://localhost:5000/api/communities"`, cancels `baseURL`.

Setting [`baseURL: config.url`](https://github.com/inveniosoftware/react-searchkit/blob/001592c8edea81db429ae1be5bbb1d42c3998671/src/lib/api/contrib/invenio/InvenioSearchApi.js#L48) and then expanding the config via `...config`, is the equivalent of:

```javascript
const axiosConfig = {
  baseURL: config.url,
  url: config.url,
};
```

When a relative `url` is used (e.g. `url: "/api/communities"`), this causes the final requests to be made to `baseURL + url = "/api/communities/api/communities"`.

**Comment by slint** [comment]
After some discussion with @zzacharo (CC @ntarocco), it is actually possible to have the desired behaviour by passing both keys to the `InvenioSearchApi` class:

```javascript
const searchApi = new InvenioSearchApi({
  baseURL: "https://localhost:5000/api/communities",
  url: "",
})
```

In general though, the discussion should be about whether to provide a wrapper around the `axios` config (which is the case now because of the special use of the `url` parameter), or to define what kind of arguments are specific to the class and have the rest of them be directly passed to the `axios` config.

**Comment by ntarocco** [comment]
In the initial discussions when designing `react-searchkit`, we did not want to have a wrapper of `axios` and define a specific subset of `axios` config to pass. That `url/baseUrl` has been changed afterwards.
Honestly I find `baseUrl`  and `url` very confusing in `axios`: one is the baseUrl indeed, but the other one is for me more a [path or a pathname](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL).
I would come back to the initial implementation and allow to pass config directly to `axios` without this manipulation of url/baseUrl introduced later on, so it is clear that you have to inject `axios` config.
